### ISSUE TITLE
Small bug fix

### ISSUE THREAD

**Issue by AndreaLabeljoy** [LanceMcCarthy/CustomMauiExamples#14]
Hi all,

I've been trying this demo and wanted to report a small bug fix for Windows.
The bug manifests when you resize the print-preview window.

The offending line is in `PrintHelper.Windows.cs/AddOnePrintPreviewPage`.

I've changed:
`_PrintPreviewPages.Add(i, print);`

to:
`if (!_PrintPreviewPages.ContainsKey(i))  _PrintPreviewPages.Add(i, print);`

Other than that, great job Lance.
Thank you.

**Comment by LanceMcCarthy** [comment]
I can't take full credit for everything, it's been a work in progress over the years and contributions from others (like you) along the way :)

Regardless, thank you for taking the time to share this with me, I'll update the code ASAP.
