### ISSUE TITLE
Persistent Blurriness Issue in Document Printing for Windows

### ISSUE THREAD

**Issue by AnshQTK** [LanceMcCarthy/CustomMauiExamples#16]
Hi,
 
I have identified a persistent issue where printed labels exhibit blurriness when utilizing the PrintHelper within the application. Interestingly, the problem does not occur when I download the PDF from the app to my computer and print it separately, resulting in clear and legible labels. I have not changed any code in the helper class.

In the accompanying image, the label on the left side was printed after downloading and printing without using the app, displaying a notably higher clarity. In contrast, the label on the right side, printed using the app's PrintHelper, appear blurry, rendering the barcode unreadable.

Thank you in advance.

![IMG_20231025_135432_341~2](https://github.com/LanceMcCarthy/CustomMauiExamples/assets/134741922/b494b1c4-c8c6-4899-89ba-998b24133d6c)

**Comment by LanceMcCarthy** [comment]
This is interesting, it seems to be due to the WinUI 3 APIs being used to insert the image data into the print canvas: https://github.com/LanceMcCarthy/CustomMauiExamples/blob/df90c3347f16a378982dd628645c44e0b58ec0da/src/DocumentPrinting/DocumentPrinting/Helpers/PrintHelper.Windows.cs#L170-L179 

Unfortunately, I'm not able to assist you with this as this problem is outside the scope of just an introductory demo. The good news is I do know where you can ask for help:

1. Go to WinUI 3's forums at https://learn.microsoft.com/en-us/answers/tags/184/windows-app-sdk
2. Ask Microsoft engineers the same question you did above. INclude the images, description and the code that prints the document (this class https://github.com/LanceMcCarthy/CustomMauiExamples/blob/main/src/DocumentPrinting/DocumentPrinting/Helpers/PrintHelper.Windows.cs).

*Important*: If you do get improved code, please be sure to come back here and share the information so that I can update the demo app for everyone else to get the improvements, too.

**Comment by AnshQTK** [comment]
Thank you for your insights and pointing out the potential cause of the blurriness issue in document printing. I will follow your suggestion and post the query along with the code and details on WinUI 3's forums.

I appreciate your assistance, and I will be sure to update this platform with any improvements obtained.

**Comment by AnshQTK** [comment]
Hi Lance,

I wanted to share the solution I discovered, which wasn't readily available online. Initially, I attempted to save the ras (InMemoryRandomAccessStream) image then checked if it provided the desired high-quality output. 

However, it turned out that the quality was not up to par. So, I modified the code to improve the output quality.In the imageCtrl, I set the actual height and width:

```
using var pdfPage = this.sourcePdfDocument.GetPage(uint.Parse(i.ToString()));
    var width = pdfPage.Size.Width;
    var height = pdfPage.Size.Height;
    var imageCtrl = new Image();
    var scale = 10;
    var renderOptions = new PdfPageRenderOptions();

    renderOptions.DestinationWidth = (uint)(width * scale);
    renderOptions.DestinationHeight = (uint)(height * scale);

    using (var stream = new InMemoryRandomAccessStream())
    {
        await pdfPage.RenderToStreamAsync(stream, renderOptions);
        var bitmapImage = new BitmapImage();
        await bitmapImage.SetSourceAsync(stream);
        imageCtrl.Source = bitmapImage;
    }

    imageCtrl.Height = height;
    imageCtrl.Width = width;
    printDocument.AddPage(imageCtrl);

```

**Comment by LanceMcCarthy** [comment]
This is AMAZING NEWS!

I was the one who mentioned to Ivan that there's probably a way to increase the DPI of the ImageCtrl that is used to stream the PDF page into, but I had not personally found a way to do it.

So thank you for coming back to share this, it will make many folks very happy and I'll be sure to tag you in the commit to give you full credit for it.

**Comment by LanceMcCarthy** [comment]
For anyone else visiting this thread, I've pushed the changes to the https://github.com/LanceMcCarthy/CustomMauiExamples/tree/improve-printing-resolution branch. Once I have enough time to thoroughly testing it, I will merge it into `main`.

As to what is different... we are using the PDF document's size values for the `Image` control 's dimensions. 

Before
https://github.com/LanceMcCarthy/CustomMauiExamples/blob/0fcd8c89a46d140e0c679ca9c081fe033ea4107c/src/DocumentPrinting/DocumentPrinting/Helpers/PrintHelper.Windows.cs#L132-L133

After
https://github.com/LanceMcCarthy/CustomMauiExamples/blob/8b039ae48a0cf0addb1abb7ff89d621ee024ce1e/src/DocumentPrinting/DocumentPrinting/Helpers/PrintHelper.Windows.cs#L181-L183

**Comment by LanceMcCarthy** [comment]
Okay, so I've had an opportunity to play around with these settings and an original issue has resurfaced.... the scale doesn't match the monitor's display resolution, so you end up getting a result like this

> my monitor is currently using 200% scaling, so the result is the PDF contents is 1/2 the size.

![image](https://github.com/LanceMcCarthy/CustomMauiExamples/assets/3520532/3b8bae98-c263-4781-856d-dd47a8f14057)

So what I will do is merge in changes that has code for both approaches, but still use the scale factor to properly fit the PDF into the Canvas
